### ISSUE TITLE
Possible typo in MakeBrushWindings

### ISSUE THREAD

**Issue by m-x-d** [qbism/q2tools-220#1]
https://github.com/qbism/q2tools-220/blob/f8f582fc02196955584542c95de8a45a138c9e42/qbsp3/map.c#L529
https://github.com/qbism/q2tools-220/blob/f8f582fc02196955584542c95de8a45a138c9e42/qbsp3/map.c#L531

Souldn't these be mins[i] and maxs[i] instead of mins[0] and maxs[0]?

**Comment by qbism** [comment]
This is from original ID source, but it does look like a typo.  Will look into it further.

**Comment by qbism** [comment]
Fixed in commit.
