### ISSUE TITLE
Support for mist contents to be single-sided - possible ?

### ISSUE THREAD

**Issue by motorsep** [qbism/q2tools-220#18]
With all the improvements that were added to these tools (and Q2RTX engine fork) we finally have first run of AD Sepulcher:

https://www.youtube.com/watch?v=uQ53oRGxJJ4

As you can see, the brushes with vines texture don't really look proper because in Q2 (from what I understand) brushes with mist content are always double sided. 

Would it be possible to add a contents (or surface?) flag, so that when 4bsp compiler finds mist content with such additional flag, it will make such brush face to be single-sided (or whole brush rather).

Thanks

**Comment by qbism** [comment]
Instead of one of the unused flags, combo contents flags like AUX + MIST may be more supported by map editors.  AUX is available in Trenchbroom and probably other editors but is not used AFAIK.  I've started looking into it.  As we found with SKIP, the compiler will override contents flags based on certain face flags.

**Comment by motorsep** [comment]
This is what's available in TB:
![image](https://user-images.githubusercontent.com/1927918/131207281-ecdfa9ee-3aee-4598-878d-2802e3bb70c6.png)
![image](https://user-images.githubusercontent.com/1927918/131207284-8fd9a09e-797d-450f-8dab-ebd4a3a987ef.png)

and this is NetRadiant Custom:
![image](https://user-images.githubusercontent.com/1927918/131207316-a3157ef7-6298-47dc-9b1a-4c5ae46948e3.png)

@Paril What do you think?

**Comment by qbism** [comment]
Please verify this is resolved in latest commit.  Add AUX content flag to turn off backface rendering of MIST.  This turned out to be the simplest in terms of code and is compatible with current TrenchBroom.

**Comment by motorsep** [comment]
Unfortunately in RTX it comes out double sided because of the shader. The one on the right was suppose to be AUX + MIST. When testing in GL renderer (still Q2RTX engine) - both are single sided :/ 

![image](https://user-images.githubusercontent.com/1927918/131933507-4ea1fa8f-f34f-4c72-93d5-70a10b71e742.png)

![quake055](https://user-images.githubusercontent.com/1927918/131933881-39a4a18f-59d1-4ac1-be21-8f784f2399e5.png)

![quake054](https://user-images.githubusercontent.com/1927918/131933905-05ca28a6-f80f-464d-b35b-d2087b677491.png)

**Comment by qbism** [comment]
Here's regular q2pro left to right-  
1.  no content flags (set to CONTENTS_WINDOW by bsp)
2. AUX+MIST
3. MIST
![pic020](https://user-images.githubusercontent.com/1802223/131940683-83954415-9756-49ef-a225-1d458d89a4f0.jpg)

**Comment by motorsep** [comment]
This is in GL mode:

https://www.youtube.com/watch?v=l6-RVrZRYYg

This is the map/bsp (below). Please see if you get different results (or maybe I am doing something wrong):
[q2_q1start.zip](https://github.com/qbism/q2tools-220/files/7103050/q2_q1start.zip)

Q2RTX can run in GL mode, no need for RTX hardware.

**Comment by qbism** [comment]
Would not suggest mixing clip texture + anything else.  Rather, use a trans texture on the other sides (solid color 255).  
http://maps.rcmd.org/tutorials/q2_palette_textures/trans.wal
See explanation here: http://maps.rcmd.org/tutorials/q2_palette_textures/

**Comment by motorsep** [comment]
Alright, I tried it again and it still fails. 4vis is butchering it. I had to use q2pro instead of q2rtx to be able to load unvis'ed BSP:

4bsp, no 4vis:
https://www.youtube.com/watch?v=_sAFu2SnUd4

4bsp + 4vis:
https://www.youtube.com/watch?v=PWZFTgdUoXg

So it kinda works, but not 100%, so to speak :)

**Comment by qbism** [comment]
OK, I'll look at it again and post a start.map + .bsp

**Comment by qbism** [comment]
In the video, guessing there's still a clip texture on the bottom.  Stock q2pro needs a small modification to get non-translucent fence textures.  This will kick in if both TRANS33 and TRANS66 are flagged.  Or else use SURF_TRANS66 only and it will be 66% transparent.    

static uint32_t color_for_surface(mface_t *surf)
{
    if ((surf->drawflags & SURF_TRANS33) && (surf->drawflags & SURF_TRANS66))  //qb: so alphamask is not transparent
     return U32_WHITE;

    if (surf->drawflags & SURF_TRANS33)
        return gl_static.inverse_intensity_33;

    if (surf->drawflags & SURF_TRANS66)
        return gl_static.inverse_intensity_66;

    if (surf->drawflags & SURF_WARP)
        return gl_static.inverse_intensity_100;

    return U32_WHITE;
}

In the attached map,  left block is MIST, center is unflagged (solid), and right is AUX+MIST

[start-test.zip](https://github.com/qbism/q2tools-220/files/7110372/start-test.zip)

![quake000](https://user-images.githubusercontent.com/1802223/132105384-68a1d3bd-62ef-4ebb-8fe7-606c0093db1e.jpg)

**Comment by motorsep** [comment]
> In the video, guessing there's still a clip texture on the bottom

No, it's the one you provided (trans.wal)

**Comment by qbism** [comment]
If any issues remain, please submit an example .map and .bsp

**Comment by motorsep** [comment]
You didn't vis your test map though.. The issue isn't with 4bsp not supporting this case, it's 4vis messing it up. And since bsp needs to be vis'ed, you get this issue I've been illustrating.
