### ISSUE TITLE
Texture projection still not 100% accurate to valve-220

### ISSUE THREAD

**Issue by FifthElphant** [qbism/q2tools-220#24]
Skewed faces either broken or not support currently it seems

images and example map attached

![1](https://user-images.githubusercontent.com/3835468/178132656-992f22b4-d546-4c81-9dd3-375af04d38c7.jpg)
![2](https://user-images.githubusercontent.com/3835468/178132657-acb32208-db39-4e05-b1b9-e1b0bf70e9e7.jpg)
[q2test.zip](https://github.com/qbism/q2tools-220/files/9078503/q2test.zip)
.

**Comment by qbism** [comment]
Quark has their own format that no compiler tool supports AFAIK.  Or please send a link to a qbsp3 that does.  Open this test map in Trenchbroom to see what I mean.  (edit: And does the .map file look correct reimported into Quark?)

**Comment by qbism** [comment]
The standard v220 face format:
( x1 y1 z1 ) ( x2 y2 z2 ) ( x3 y3 z3 ) TEXTURE_NAME [ tx1 ty1 tz1 toffs1 ] [ tx2 ty2 tz2 toffs2 ] rotation scaleX scaleY

Quark, with three extra numbers for each face:
( 192 80 -64 ) ( 192 -192 -64 ) ( 192 -192 0 ) e2u3/floor2_6 [ 0.00000 1.00000 0.00000 0.00000 ]  [ 0.00000 0.00000 -1.00000 0.00000 ]  0  1.00000 1.00000 0 0 0
