### ISSUE TITLE
Request: Make qdir and gamedir able to be manually set with parameters

### ISSUE THREAD

**Issue by aapokaapo** [qbism/q2tools-220#25]
Make qdir and gamedir able to be manually set with parameters -qdir and -gamedir respectively. Right now -basedir doesn't seem to do anything. Also could 4rad search for colormap.pcx from the directory 4rad is located in if it fails to find it in ${basedir}/pics/

**Comment by qbism** [comment]
4rad must be in gamedir (usually quake2) to work as intended.  qdir, gamedir, and moddir are automatically determined.  -basedir may be set from the command line.

Example- a map in baseq2 using textures from 3tctf (Linux format):
./4rad -basedir 3tctf  baseq2/maps/mymap

In a custom mod folder:
/4rad -basedir 3tctf  mymod/maps/mymap

4rad will look for textures in basedir first (3tctf) then in moddir (mymod).  It only looks for colormap.pcx in moddir/pics.  I think that is required because it's the only place the game will look.

**Comment by qbism** [comment]
I'm marking this closed and adding the response to the readme.  I guess many people tend to put tools in the /baseq2 folder (self included).  Please open a new issue with an example if there are still problems.

**Comment by aapokaapo** [comment]
Thanks for the quick replies! I want to keep my mapping files at where the editor is, not with the gamefiles. In my opinion the gamefiles should only have files necessary to run and play the game.

Example:
My editor is in C:/Games/Trenchbroom/
My '.map'-files are in C:/Games/Trenchbroom/maps
My compilers are in C:/Games/Trenchbroom/tools/
My game/modfiles are in C:/Games/Paintball2/pball/ (my baseq2 dir)

Cmdline:
../Trenchbroom/tools/4rad -basedir C:/Games/Paintball2/pball ../Trenchbroom/maps/mymap
=> Compiler sets gamedir to ..Trenchbroom/tools/ and moddir to ../Trenchbroom/tools/..
=> compiler can't find colormap.pcx and raises an error

What I expected to be able to do:
../Trenchbroom/tools/4rad -basedir C:/Games/Paintball2/pball -gamedir C:/Games/Paintball2 ../Trenchbroom/maps/mymap
=> Compiler finds all the game files and compiles the map correctly

I used blarghrad before this compiler and it lets me set the gamedir with -gamedir parameter, regardless of the compiler location thus letting me keep the mapping files and game files separated.

Sorry for the long post.

**Comment by qbism** [comment]
Thanks for the clear description.  I think it would be a good feature.  Current operation expects map files to be located in maps file under gamedir.  I guess the same ability is needed by 4bsp to find textures for reading the flags.

**Comment by aapokaapo** [comment]
Amazing to see someone still work on compilers for over 2 decades old game. Yes 4bsp would need it too. Keep up the good work! :)

**Comment by qbism** [comment]
Completed per https://github.com/qbism/q2tools-220/commit/330e82bb87b08949c8fceb5601d9174a61eb864a
