### ISSUE TITLE
PAK reading issue (platform-specific)

### ISSUE THREAD

**Issue by RaZeR-RBI** [qbism/q2tools-220#30]
`TryLoadFileFromPak` fails for me because on my machine size of `pakheader_t` and `pakentry_t` structs is wrong due to `long` being 8 byte long instead of 4 ([ref](https://quakewiki.org/wiki/.pak)), which causes wrong data being read and malloc failing because of that. Changing `long` to `uint32_t` in these structs fixes the issue.

**Comment by qbism** [comment]
Good catch.  I will search for other long in source and replace
