### ISSUE TITLE
Latest release binaries removed?

### ISSUE THREAD

**Issue by SirYodaJedi** [qbism/q2tools-220#34]
The binaries for the [16 Feb 2023 release](https://github.com/qbism/q2tools-220/releases/tag/02-16-23) were removed from the releases page, and the release was renamed and marked as a "pre-release". Is there a particular reason for this? I downloaded it while it was still available, but someone else pointed out the change on Discord.

**Comment by qbism** [comment]
Yes, see issue #35.
