### ISSUE TITLE
[qbsp3, mapformat 220] Texture rotation ignored when applying origfix.

### ISSUE THREAD

**Issue by m-x-d** [qbism/q2tools-220#4]
Texture rotation stored in UVaxis is ignored when applying origfix.

In editor:
![origfix_bug_jack](https://user-images.githubusercontent.com/7252064/41095723-0a734808-6a5b-11e8-9f04-f23978ea1ce0.jpg)

Ingame:
![origfix_bug_kmq2](https://user-images.githubusercontent.com/7252064/41095766-3154dc2a-6a5b-11e8-80ee-b41ad541e82a.jpg)

The map: 
[orig_bug.zip](https://github.com/qbism/q2tools-220/files/2080114/orig_bug.zip)

**Comment by qbism** [comment]
It appears texture rotation with origin brush is always ignored.  It doesn't matter whether or not -origfix is applied, which itself is working. Origfix applies a correction to origin and scale but does not change rotation.
