### ISSUE TITLE
Sunlight question

### ISSUE THREAD

**Issue by JafiMapping** [qbism/q2tools-220#40]
Hello!
Nice work for your 220 q2tools!
I'm a mapper here!
4rad seems to manage sunlight. I tried to use the old arghrad setting for this, but it dosent seems to work. Is there a documentation somewhere?
Ty

**Comment by qbism** [comment]
The sun system is based on DeWan's qrad3.
Screenshots attached an gist of the tutorial found below:
http://tastyspleen.net/~panjoo/rust/tutorials/sun/The%20sun%20is%20neater%20than%20you%20thought!.htm

First, create a light and target it to an info_null.  This will be your sun's angle.

Next, add the _sun key to your worldspawn, and enter the targetname of the info_null.

Make sure all of your sky textures have the light flag checked and a light value.

Add the _sun_light value to your worldspawn, and give it a light value.

Add the _sun_ambient value to your worldspawn, and give it a light value.

Add a _sun_color value to your worldspawn, and give it a value.

![sun-shot-1](https://user-images.githubusercontent.com/1802223/230701300-05d6d4c5-9d47-44bf-a84d-e53c49e5a0cd.png)
![sun-shot-2](https://user-images.githubusercontent.com/1802223/230701299-d5c7b2d5-51ee-4061-8c60-843e93a90120.png)
![sun-shot-3](https://user-images.githubusercontent.com/1802223/230701298-bad65171-93af-4a9c-ba2b-6dcf4251666d.png)

**Comment by JafiMapping** [comment]
Thank you!
