### ISSUE TITLE
Is there a way to -chop liquid? 

### ISSUE THREAD

**Issue by JafiMapping** [qbism/q2tools-220#41]
Because the triangles count is very heavy with liquid. 
Thank you

**Comment by qbism** [comment]
Cool idea.  Similar to chop light.  Wonder if anything is hardwired in game since vertices are moving.   I will look at this next time in code.  Do any other bsp tools implement this?

**Comment by qbism** [comment]
So liquids (SURF_WARP) faces are not chopped at all.  The effect is done by the engine.
`/*
===============
SubdivideFace

Chop up faces that are larger than we want in the surface cache
===============
*/
void SubdivideFace(node_t *node, face_t *f) {
    vec_t mins, maxs;
    vec_t v;
    int32_t axis, i;
    texinfo_t *tex;
    vec3_t temp;
    vec_t dist;
    winding_t *w, *frontw, *backw;

    if (f->merged)
        return;

    // special (non-surface cached) faces don't need subdivision
    tex = &texinfo[f->texinfo];

    if (tex->flags & (SURF_WARP | SURF_SKY)) {
        return;
    }
`

**Comment by JafiMapping** [comment]
So it's already optimized if Surf_warp texture flag is checked?
Il try to see de difference between each others. 

Thank YOu!!

**Comment by qbism** [comment]
That is correct.  BSP converts the whole map to triangles, but does not chop surf_warp smaller.  Try gl_drawtris 1 in q2pro for example.
![quake001](https://github.com/qbism/q2tools-220/assets/1802223/aa9368fd-5415-463f-b566-ebad1f67b42c)

**Comment by JafiMapping** [comment]
Thank you.  That was my concern.  I gl_showtris in KMQ2 (knightmare) and its -chop was not like you show in your picture at all. It had a huge amount of triangles.  But despite of the huge amount of triangles, I think its optimized too, because when i ran it in Quake2 XP i didnt have a fps drop issue. Because, with that engine,   when 3000  triangles are  shown, this is what happen most of the time, at least, whit my not so bad cpu. :).  The real time lightning is taking a lot of resources on that engine. Especially in combat scene.
