### ISSUE TITLE
Does these tools work with Kingpin and J.A.C.K.?

### ISSUE THREAD

**Issue by Cianez** [qbism/q2tools-220#7]
I usually run hlrad_x64.exe with "-smooth 200" on GoldSrc maps (using VHLT).
I'm asking this because even if I use "-smooth" on Kingpin, faces doesn't get smoothed at all (with the same values). Basically, "-smooth 0" or "-smooth 200" makes no difference; every rounded brush is not smoothed.
"-bounce" doesn't seem to affect the lighting either.

I'm using J.A.C.K. with these compiling options on "$light_exe":

`-extra -smooth 200 -bounce 30 "$bspdir/$file"`

Do I have to setup J.A.C.K. in a different way maybe? I'm currently using the Quake 2 profile for Kingpin and I've edited "VDKGameCfg.ini" to make the Q2 configuration read TGA files.

Any help is appreciated.

**Comment by qbism** [comment]
Thanks for the feedback.  This is multiple issues that need breaking down but I'll take the main issue as 'smooth'.  This post shows an example with '-smooth 46' and explanation:
https://qbism.com/viewtopic.php?f=5&t=58&p=32693#p32693

The tools are based on the ones distributed with J.A.C.K. and should behave the same with tga loading and bounce.  Probably need a case where bounce works as expected with another open-source qrad3 such as original q2 tools or Dewan's.

**Comment by Cianez** [comment]
I'd love to use your tools to make my maps for Kingpin once you manage to make -smooth work as intended. As of now, I don't know why because I'm not a programmer, on a 16 sided cylinder it doesn't seem to work at all...
![kingpin 2020-02-16 23-48-34-24](https://user-images.githubusercontent.com/46445923/74614279-e3ba7700-5116-11ea-9ca0-e913baff3ce6.png)
 Unless I need to guess/calculate the angle's degrees to make it work properly, but that wouldn't make it work on other angles on different brushes (or I'm missing something).

Anyway, if you're interested I'm up for some testing with your tools. You can contact me on Discord ([TC]Čiαиєz#3698) as these tools could make us Kingpin mappers' life easier.

**Comment by hypov8** [comment]
small faces have allways been hard to phong shade, even arghrad struggles to phong shade them. sky sun is also very grainy. you may just need some point lights to brighten the back/dark surfaces. also consider that one faces on the bin is likely to be 1 or 2 pixels in total for the lightmap. so phong shading will never work. thats why q3 uses vertex light on their map models. 
one other thing to consider is that the uv also needs to be calculated and will have spits where least desirable. you could export as a .obj to inspect

**Comment by hypov8** [comment]
thats how many pixels with a .75 texture stretch on the bin.. 1pixel cant be "shaded"
![lightmap_pix](https://user-images.githubusercontent.com/16630512/74622944-ca590f80-5196-11ea-8c5c-8d7b11bfe32a.jpg)

**Comment by Cianez** [comment]
It does work everytime on every shape and face's angle degree with hlrad.exe on Goldsrc games though. He's using VHLT as a base so I thought it was possible (mainly because Goldsrc and idTech2 are very similar code-wise).

**Comment by qbism** [comment]
Some engines allow lightmap scale independent of bitmap, but not stock idtech2.  Scaling the texture is a trick for small faces:
![pic006](https://user-images.githubusercontent.com/1802223/74704212-85a49700-51dd-11ea-8b85-26513033d543.jpg)

![pic005](https://user-images.githubusercontent.com/1802223/74704227-8d643b80-51dd-11ea-9dc7-ccc80f24dd85.jpg)

**Comment by Cianez** [comment]
That barrel texture I made on my screenshot is scaled to something like 0.050 (the texture's size is 1024x512), so it's very low, but nothing gets smoothed for some reason. Unless it's Kingpin's renderer not understanding the smoothing algorythm. Are the screenshots you posting from Quake 2? Maybe I can try loading your BSP on Kingpin and see if I get the same effect.

**Comment by hypov8** [comment]
it must be something you are doing with your compiles or map structure. a faulty brushes maybe? 
from the screenshots qbism posted. the tools are working
arghrad works fine when you have some texture space to work with. 
it not the kp render. its rendering a precompiled texture inside the bsp
![kingpin030](https://user-images.githubusercontent.com/16630512/74885082-cd3b4680-53c8-11ea-9805-f54c6646b25f.jpg)

**Comment by Cianez** [comment]
I've just found out that I was using values too high (`-smooth 200`). VHLT on HLRAD works "the higher the smoother", so I thought the same rule applied here.
By using `-smooth 44` I do get smoothing but not as much as I want. If I try to increase it a bit further the default value (44) I don't see any difference, and if I go even further it doesn't get smoothed at all. So I guess this can be made better?

For your info:

`-smooth 44`
![kingpin 2020-02-22 06-18-58-40](https://user-images.githubusercontent.com/46445923/75087021-64281000-553b-11ea-9a6d-547e7245ac70.png)

`-smooth 100`
![kingpin 2020-02-22 06-19-45-22](https://user-images.githubusercontent.com/46445923/75087026-773ae000-553b-11ea-88fc-8c95e008a054.png)

**Comment by qbism** [comment]
This is an angle value, clamped between 0 and 90 degrees.  200 should still work; it will be clamped to 90.  So I'll look at this.

The only way to get more smoothing is - extra.  Sometimes it helps, sometimes not.

**Comment by hypov8** [comment]
i knew your value was wrong... it seemed like you didnt read the instructions of what it actual does
if you shade at 90 deg. you will include the top of the bin and the floor in the smoothing algorithm. this will adversely effect the sides of the barrels shading.

just to clarify.. the -smooth value/angle is to decide if the face IS or ISNOT shaded with neighbor face.. On or OFF. its not the quality value

**Comment by qbism** [comment]
This is the expected behavior so have closed this issue.
