### ISSUE TITLE
Request/suggestion: Heretic II animated textures support

### ISSUE THREAD

**Issue by whirledtsar** [qbism/q2tools-220#8]
As far as I can tell, Heretic II animated textures (.m8 format) do not work with this compiler. I compiled the same map with stock compilers and qtools-220 and they were only animated in the former. The game's CD comes with a toolkit (also found [here](http://quark.sourceforge.net/download_tools.php)) with the source code of Raven's qbsp3, which should be helpful in understanding how they implemented it.

**Comment by qbism** [comment]
Attempted to add but untested.  Post any bug as a separate issue.
